### ISSUE TITLE
Bad server name

### ISSUE THREAD

**Issue by NeoMahler** [jrosdahl/miniircd#16]
I'm running miniircd-1.1 on FreeBSD, and the host is "neoneo.unixssh.com". But when I connect with HexChat to the server, it appears that I'm connected to dafthost.com:

* Hi, welcome to IRC
* Your host is dafthost.com, running version miniircd-1.1
* This server was created sometime
* dafthost.com miniircd-1.1 o o
* There are 2 users and 0 services on 1 server
* - dafthost.com Message of the day -

And here it appears the motd I set. Is this a bug or is a normal thing?

**Comment by jrosdahl** [comment]
Well, that's because miniircd asks the server about its hostname and the server says "dafthost.com". There's nothing miniircd can do about that, unfortunately. (Well, it would be possible to make miniircd take a commandline argument or configuration saying what server name to present to the client, but that isn't reasonable to do for a mini IRC server.)

**Comment by NeoMahler** [comment]
Ok, thanks for the answer.
